config/routes.rb
LinkerApp::Application.routes.draw do
  resources :link_items
  resources :visitors

end

app/models/link_item.rb
class LinkItem < ActiveRecord::Base
  attr_accessible :needs_email, :original_url, :password, :short_name

  has_many :visitors

end

app/models/visitor.rb
class Visitor < ActiveRecord::Base
  attr_accessible :email_address, :ip_address, :link_item_id, :referrer

  belongs_to :link_item

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery

  protected

  def authenticate
    authenticate_or_request_with_http_basic do |username, password|
      username == "david" && password == "secret!"
    end
  end
end

app/controllers/link_items_controller.rb
class LinkItemsController < ApplicationController

  # before_filter :authenticate, :except => :redirector


  # GET /link_items
  # GET /link_items.json
  def index
    @link_items = LinkItem.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @link_items }
    end
  end

  # GET /link_items/1
  # GET /link_items/1.json
  def show
    @link_item = LinkItem.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @link_item }
    end
  end

  # GET /link_items/new
  # GET /link_items/new.json
  def new
    @link_item = LinkItem.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @link_item }
    end
  end

  # GET /link_items/1/edit
  def edit
    @link_item = LinkItem.find(params[:id])
  end

  # POST /link_items
  # POST /link_items.json
  def create
    @link_item = LinkItem.new(params[:link_item])

    respond_to do |format|
      if @link_item.save
        format.html { redirect_to @link_item, notice: 'Link item was successfully created.' }
        format.json { render json: @link_item, status: :created, location: @link_item }
      else
        format.html { render action: "new" }
        format.json { render json: @link_item.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /link_items/1
  # PUT /link_items/1.json
  def update
    @link_item = LinkItem.find(params[:id])

    respond_to do |format|
      if @link_item.update_attributes(params[:link_item])
        format.html { redirect_to @link_item, notice: 'Link item was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @link_item.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /link_items/1
  # DELETE /link_items/1.json
  def destroy
    @link_item = LinkItem.find(params[:id])
    @link_item.destroy

    respond_to do |format|
      format.html { redirect_to link_items_url }
      format.json { head :no_content }
    end
  end
end

app/controllers/visitors_controller.rb
class VisitorsController < ApplicationController

  before_filter :authenticate, :except => [:edit, :update]

  # GET /visitors
  # GET /visitors.json
  def index
    @visitors = Visitor.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @visitors }
    end
  end

  # GET /visitors/1
  # GET /visitors/1.json
  def show
    @visitor = Visitor.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @visitor }
    end
  end

  # GET /visitors/new
  # GET /visitors/new.json
  # def new
  #   @visitor = Visitor.new

  #   respond_to do |format|
  #     format.html # new.html.erb
  #     format.json { render json: @visitor }
  #   end
  # end

  # GET /visitors/1/edit
  # This is the URL where we collect their email address
  def edit
    @visitor = Visitor.find(params[:id])
  end

  # POST /visitors
  # POST /visitors.json
  # def create
  #   @visitor = Visitor.new(params[:visitor])

  #   respond_to do |format|
  #     if @visitor.save
  #       format.html { redirect_to @visitor, notice: 'Visitor was successfully created.' }
  #       format.json { render json: @visitor, status: :created, location: @visitor }
  #     else
  #       format.html { render action: "new" }
  #       format.json { render json: @visitor.errors, status: :unprocessable_entity }
  #     end
  #   end
  # end

  # PUT /visitors/1
  # PUT /visitors/1.json
  def update
    @visitor = Visitor.find(params[:id])

    respond_to do |format|
      if @visitor.update_attributes(params[:visitor])
        format.html { redirect_to @visitor }
      end
    end
  end

  # DELETE /visitors/1
  # DELETE /visitors/1.json
  def destroy
    @visitor = Visitor.find(params[:id])
    @visitor.destroy

    respond_to do |format|
      format.html { redirect_to visitors_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/link_items_helper.rb
module LinkItemsHelper
end

app/helpers/visitors_helper.rb
module VisitorsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><%= content_for?(:title) ? yield(:title) : "LinkerApp" %></title>
    <%= csrf_meta_tags %>

    <!-- Le HTML5 shim, for IE6-8 support of HTML elements -->
    <!--[if lt IE 9]>
      <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/3.6.1/html5shiv.js" type="text/javascript"></script>
    <![endif]-->

    <%= stylesheet_link_tag "application", :media => "all" %>
  </head>
  <body>

    <div class="navbar navbar-fixed-top">
      <div class="navbar-inner">
        <div class="container">
          <a class="btn btn-navbar" data-target=".nav-collapse" data-toggle="collapse">
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </a>
          <a class="brand" href="#">LinkerApp</a>
          <div class="container nav-collapse">
            <ul class="nav">
            </ul>
          </div><!--/.nav-collapse -->
        </div>
      </div>
    </div>

    <div class="main_container container">
        <div class="row">
          <div class="span12">
            <%= bootstrap_flash %>
            <%= yield %>
          </div>
        </div><!--/row-->

      <footer>
        <p>&copy; Company 2013</p>
      </footer>

    </div> <!-- /container -->

    <!-- Javascripts
    ================================================== -->
    <!-- Placed at the end of the document so the pages load faster -->
    <%= javascript_include_tag "application" %>

  </body>
</html>

app/views/link_items/_form.html.erb
<%= form_for @link_item, :html => { :class => 'form-horizontal' } do |f| %>
  <div class="control-group">
    <%= f.label :original_url, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :original_url, :class => 'text_field' %>
    </div>
  </div>
  <div class="control-group">
    <%= f.label :short_name, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :short_name, :class => 'text_field' %>
    </div>
  </div>
  <div class="control-group">
    <%= f.label :password, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :password, :class => 'text_field' %>
    </div>
  </div>
  <div class="control-group">
    <%= f.label :needs_email, :class => 'control-label' %>
    <div class="controls">
      <%= f.check_box :needs_email, :class => 'check_box' %>
    </div>
  </div>

  <div class="form-actions">
    <%= f.submit nil, :class => 'btn btn-primary' %>
    <%= link_to t('.cancel', :default => t("helpers.links.cancel")),
                link_items_path, :class => 'btn' %>
  </div>
<% end %>

app/views/link_items/edit.html.erb
<%- model_class = LinkItem -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.edit', 'Edit %{model}'], :model => model_class.model_name.human %></h1>
</div>
<%= render :partial => 'form' %>

app/views/link_items/index.html.erb
<%- model_class = LinkItem -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.pluralize %></h1>
</div>
<table class="table table-striped">
  <thead>
    <tr>
      <th><%= model_class.human_attribute_name(:id) %></th>
      <th><%= model_class.human_attribute_name(:original_url) %></th>
      <th><%= model_class.human_attribute_name(:short_name) %></th>
      <th><%= model_class.human_attribute_name(:password) %></th>
      <th><%= model_class.human_attribute_name(:needs_email) %></th>
      <th><%= model_class.human_attribute_name(:created_at) %></th>
      <th><%=t '.actions', :default => t("helpers.actions") %></th>
    </tr>
  </thead>
  <tbody>
    <% @link_items.each do |link_item| %>
      <tr>
        <td><%= link_to link_item.id, link_item_path(link_item) %></td>
        <td><%= link_item.original_url %></td>
        <td><%= link_item.short_name %></td>
        <td><%= link_item.password %></td>
        <td><%= link_item.needs_email %></td>
        <td><%=l link_item.created_at %></td>
        <td>
          <%= link_to t('.edit', :default => t("helpers.links.edit")),
                      edit_link_item_path(link_item), :class => 'btn btn-mini' %>
          <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
                      link_item_path(link_item),
                      :method => :delete,
                      :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
                      :class => 'btn btn-mini btn-danger' %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<%= link_to t('.new', :default => t("helpers.links.new")),
            new_link_item_path,
            :class => 'btn btn-primary' %>

app/views/link_items/new.html.erb
<%- model_class = LinkItem -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.new', 'New %{model}'], :model => model_class.model_name.human %></h1>
</div>
<%= render :partial => 'form' %>

app/views/link_items/show.html.erb
<%- model_class = LinkItem -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human %></h1>
</div>

<dl class="dl-horizontal">
  <dt><strong><%= model_class.human_attribute_name(:original_url) %>:</strong></dt>
  <dd><%= @link_item.original_url %></dd>
  <dt><strong><%= model_class.human_attribute_name(:short_name) %>:</strong></dt>
  <dd><%= @link_item.short_name %></dd>
  <dt><strong><%= model_class.human_attribute_name(:password) %>:</strong></dt>
  <dd><%= @link_item.password %></dd>
  <dt><strong><%= model_class.human_attribute_name(:needs_email) %>:</strong></dt>
  <dd><%= @link_item.needs_email %></dd>
</dl>

<div class="form-actions">
  <%= link_to t('.back', :default => t("helpers.links.back")),
              link_items_path, :class => 'btn'  %>
  <%= link_to t('.edit', :default => t("helpers.links.edit")),
              edit_link_item_path(@link_item), :class => 'btn' %>
  <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
              link_item_path(@link_item),
              :method => 'delete',
              :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
              :class => 'btn btn-danger' %>
</div>

app/views/visitors/_form.html.erb
<%= form_for @visitor, :html => { :class => 'form-horizontal' } do |f| %>
  <div class="control-group">
    <%= f.label :email_address, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :email_address, :class => 'text_field' %>
    </div>
  </div>
  <div class="form-actions">
    <%= f.submit "Go To Link", :class => 'btn btn-primary' %>
  </div>
<% end %>

app/views/visitors/edit.html.erb
<%- model_class = Visitor -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.edit', 'Edit %{model}'], :model => model_class.model_name.human %></h1>
</div>
<%= render :partial => 'form' %>

app/views/visitors/index.html.erb
<%- model_class = Visitor -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.pluralize %></h1>
</div>
<table class="table table-striped">
  <thead>
    <tr>
      <th><%= model_class.human_attribute_name(:id) %></th>
      <th><%= model_class.human_attribute_name(:ip_address) %></th>
      <th><%= model_class.human_attribute_name(:email_address) %></th>
      <th><%= model_class.human_attribute_name(:referrer) %></th>
      <th><%= model_class.human_attribute_name(:link_item_id) %></th>
      <th><%= model_class.human_attribute_name(:created_at) %></th>
      <th><%=t '.actions', :default => t("helpers.actions") %></th>
    </tr>
  </thead>
  <tbody>
    <% @visitors.each do |visitor| %>
      <tr>
        <td><%= link_to visitor.id, visitor_path(visitor) %></td>
        <td><%= visitor.ip_address %></td>
        <td><%= visitor.email_address %></td>
        <td><%= visitor.referrer %></td>
        <% if visitor.link_item %>
          <td><%= link_to(visitor.link_item.short_name, link_item_path(visitor.link_item)) %></td>
        <% else %>
          <td>Link Removed</td>
        <% end %>
        <td><%=l visitor.created_at %></td>
        <td>
          <%= link_to t('.edit', :default => t("helpers.links.edit")),
                      edit_visitor_path(visitor), :class => 'btn btn-mini' %>
          <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
                      visitor_path(visitor),
                      :method => :delete,
                      :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
                      :class => 'btn btn-mini btn-danger' %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<%= link_to t('.new', :default => t("helpers.links.new")),
            new_visitor_path,
            :class => 'btn btn-primary' %>

app/views/visitors/new.html.erb
<%- model_class = Visitor -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.new', 'New %{model}'], :model => model_class.model_name.human %></h1>
</div>
<%= render :partial => 'form' %>

app/views/visitors/show.html.erb
<%- model_class = Visitor -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human %></h1>
</div>

<dl class="dl-horizontal">
  <dt><strong><%= model_class.human_attribute_name(:ip_address) %>:</strong></dt>
  <dd><%= @visitor.ip_address %></dd>
  <dt><strong><%= model_class.human_attribute_name(:email_address) %>:</strong></dt>
  <dd><%= @visitor.email_address %></dd>
  <dt><strong><%= model_class.human_attribute_name(:referrer) %>:</strong></dt>
  <dd><%= @visitor.referrer %></dd>
  <dt><strong><%= model_class.human_attribute_name(:link_item_id) %>:</strong></dt>
  <dd><%= @visitor.link_item_id %></dd>
</dl>

<div class="form-actions">
  <%= link_to t('.back', :default => t("helpers.links.back")),
              visitors_path, :class => 'btn'  %>
  <%= link_to t('.edit', :default => t("helpers.links.edit")),
              edit_visitor_path(@visitor), :class => 'btn' %>
  <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
              visitor_path(@visitor),
              :method => 'delete',
              :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
              :class => 'btn btn-danger' %>
</div>